// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JoinCommand.proto

package dst.objects;

public final class JoinCommand {
	private JoinCommand() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface CommandOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required string commndVal = 1;
		/**
		 * <code>required string commndVal = 1;</code>
		 */
		boolean hasCommndVal();

		/**
		 * <code>required string commndVal = 1;</code>
		 */
		java.lang.String getCommndVal();

		/**
		 * <code>required string commndVal = 1;</code>
		 */
		com.google.protobuf.ByteString getCommndValBytes();

		// required string id = 2;
		/**
		 * <code>required string id = 2;</code>
		 */
		boolean hasId();

		/**
		 * <code>required string id = 2;</code>
		 */
		java.lang.String getId();

		/**
		 * <code>required string id = 2;</code>
		 */
		com.google.protobuf.ByteString getIdBytes();

		// optional string lookUp = 3;
		/**
		 * <code>optional string lookUp = 3;</code>
		 */
		boolean hasLookUp();

		/**
		 * <code>optional string lookUp = 3;</code>
		 */
		java.lang.String getLookUp();

		/**
		 * <code>optional string lookUp = 3;</code>
		 */
		com.google.protobuf.ByteString getLookUpBytes();

		// optional string tcpEndPoint = 4;
		/**
		 * <code>optional string tcpEndPoint = 4;</code>
		 */
		boolean hasTcpEndPoint();

		/**
		 * <code>optional string tcpEndPoint = 4;</code>
		 */
		java.lang.String getTcpEndPoint();

		/**
		 * <code>optional string tcpEndPoint = 4;</code>
		 */
		com.google.protobuf.ByteString getTcpEndPointBytes();
	}

	/**
	 * Protobuf type {@code Command}
	 */
	public static final class Command extends
			com.google.protobuf.GeneratedMessage implements CommandOrBuilder {
		// Use Command.newBuilder() to construct.
		private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private Command(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final Command defaultInstance;

		public static Command getDefaultInstance() {
			return defaultInstance;
		}

		public Command getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Command(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						commndVal_ = input.readBytes();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						id_ = input.readBytes();
						break;
					}
					case 26: {
						bitField0_ |= 0x00000004;
						lookUp_ = input.readBytes();
						break;
					}
					case 34: {
						bitField0_ |= 0x00000008;
						tcpEndPoint_ = input.readBytes();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return dst.objects.JoinCommand.internal_static_Command_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return dst.objects.JoinCommand.internal_static_Command_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							dst.objects.JoinCommand.Command.class,
							dst.objects.JoinCommand.Command.Builder.class);
		}

		public static com.google.protobuf.Parser<Command> PARSER = new com.google.protobuf.AbstractParser<Command>() {
			public Command parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Command(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<Command> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required string commndVal = 1;
		public static final int COMMNDVAL_FIELD_NUMBER = 1;
		private java.lang.Object commndVal_;

		/**
		 * <code>required string commndVal = 1;</code>
		 */
		public boolean hasCommndVal() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required string commndVal = 1;</code>
		 */
		public java.lang.String getCommndVal() {
			java.lang.Object ref = commndVal_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					commndVal_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string commndVal = 1;</code>
		 */
		public com.google.protobuf.ByteString getCommndValBytes() {
			java.lang.Object ref = commndVal_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				commndVal_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string id = 2;
		public static final int ID_FIELD_NUMBER = 2;
		private java.lang.Object id_;

		/**
		 * <code>required string id = 2;</code>
		 */
		public boolean hasId() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required string id = 2;</code>
		 */
		public java.lang.String getId() {
			java.lang.Object ref = id_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					id_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string id = 2;</code>
		 */
		public com.google.protobuf.ByteString getIdBytes() {
			java.lang.Object ref = id_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				id_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string lookUp = 3;
		public static final int LOOKUP_FIELD_NUMBER = 3;
		private java.lang.Object lookUp_;

		/**
		 * <code>optional string lookUp = 3;</code>
		 */
		public boolean hasLookUp() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>optional string lookUp = 3;</code>
		 */
		public java.lang.String getLookUp() {
			java.lang.Object ref = lookUp_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					lookUp_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string lookUp = 3;</code>
		 */
		public com.google.protobuf.ByteString getLookUpBytes() {
			java.lang.Object ref = lookUp_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				lookUp_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string tcpEndPoint = 4;
		public static final int TCPENDPOINT_FIELD_NUMBER = 4;
		private java.lang.Object tcpEndPoint_;

		/**
		 * <code>optional string tcpEndPoint = 4;</code>
		 */
		public boolean hasTcpEndPoint() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		/**
		 * <code>optional string tcpEndPoint = 4;</code>
		 */
		public java.lang.String getTcpEndPoint() {
			java.lang.Object ref = tcpEndPoint_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					tcpEndPoint_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string tcpEndPoint = 4;</code>
		 */
		public com.google.protobuf.ByteString getTcpEndPointBytes() {
			java.lang.Object ref = tcpEndPoint_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				tcpEndPoint_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			commndVal_ = "";
			id_ = "";
			lookUp_ = "";
			tcpEndPoint_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasCommndVal()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getCommndValBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getIdBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getLookUpBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBytes(4, getTcpEndPointBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getCommndValBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getIdBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						3, getLookUpBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						4, getTcpEndPointBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static dst.objects.JoinCommand.Command parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static dst.objects.JoinCommand.Command parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static dst.objects.JoinCommand.Command parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static dst.objects.JoinCommand.Command parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static dst.objects.JoinCommand.Command parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static dst.objects.JoinCommand.Command parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static dst.objects.JoinCommand.Command parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static dst.objects.JoinCommand.Command parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static dst.objects.JoinCommand.Command parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static dst.objects.JoinCommand.Command parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				dst.objects.JoinCommand.Command prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code Command}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				dst.objects.JoinCommand.CommandOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return dst.objects.JoinCommand.internal_static_Command_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return dst.objects.JoinCommand.internal_static_Command_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								dst.objects.JoinCommand.Command.class,
								dst.objects.JoinCommand.Command.Builder.class);
			}

			// Construct using dst.objects.JoinCommand.Command.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				commndVal_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				lookUp_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				tcpEndPoint_ = "";
				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return dst.objects.JoinCommand.internal_static_Command_descriptor;
			}

			public dst.objects.JoinCommand.Command getDefaultInstanceForType() {
				return dst.objects.JoinCommand.Command.getDefaultInstance();
			}

			public dst.objects.JoinCommand.Command build() {
				dst.objects.JoinCommand.Command result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public dst.objects.JoinCommand.Command buildPartial() {
				dst.objects.JoinCommand.Command result = new dst.objects.JoinCommand.Command(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.commndVal_ = commndVal_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.lookUp_ = lookUp_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.tcpEndPoint_ = tcpEndPoint_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof dst.objects.JoinCommand.Command) {
					return mergeFrom((dst.objects.JoinCommand.Command) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(dst.objects.JoinCommand.Command other) {
				if (other == dst.objects.JoinCommand.Command
						.getDefaultInstance())
					return this;
				if (other.hasCommndVal()) {
					bitField0_ |= 0x00000001;
					commndVal_ = other.commndVal_;
					onChanged();
				}
				if (other.hasId()) {
					bitField0_ |= 0x00000002;
					id_ = other.id_;
					onChanged();
				}
				if (other.hasLookUp()) {
					bitField0_ |= 0x00000004;
					lookUp_ = other.lookUp_;
					onChanged();
				}
				if (other.hasTcpEndPoint()) {
					bitField0_ |= 0x00000008;
					tcpEndPoint_ = other.tcpEndPoint_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasCommndVal()) {

					return false;
				}
				if (!hasId()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				dst.objects.JoinCommand.Command parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (dst.objects.JoinCommand.Command) e
							.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required string commndVal = 1;
			private java.lang.Object commndVal_ = "";

			/**
			 * <code>required string commndVal = 1;</code>
			 */
			public boolean hasCommndVal() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string commndVal = 1;</code>
			 */
			public java.lang.String getCommndVal() {
				java.lang.Object ref = commndVal_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					commndVal_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string commndVal = 1;</code>
			 */
			public com.google.protobuf.ByteString getCommndValBytes() {
				java.lang.Object ref = commndVal_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					commndVal_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string commndVal = 1;</code>
			 */
			public Builder setCommndVal(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				commndVal_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string commndVal = 1;</code>
			 */
			public Builder clearCommndVal() {
				bitField0_ = (bitField0_ & ~0x00000001);
				commndVal_ = getDefaultInstance().getCommndVal();
				onChanged();
				return this;
			}

			/**
			 * <code>required string commndVal = 1;</code>
			 */
			public Builder setCommndValBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				commndVal_ = value;
				onChanged();
				return this;
			}

			// required string id = 2;
			private java.lang.Object id_ = "";

			/**
			 * <code>required string id = 2;</code>
			 */
			public boolean hasId() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required string id = 2;</code>
			 */
			public java.lang.String getId() {
				java.lang.Object ref = id_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					id_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string id = 2;</code>
			 */
			public com.google.protobuf.ByteString getIdBytes() {
				java.lang.Object ref = id_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					id_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string id = 2;</code>
			 */
			public Builder setId(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string id = 2;</code>
			 */
			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000002);
				id_ = getDefaultInstance().getId();
				onChanged();
				return this;
			}

			/**
			 * <code>required string id = 2;</code>
			 */
			public Builder setIdBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				id_ = value;
				onChanged();
				return this;
			}

			// optional string lookUp = 3;
			private java.lang.Object lookUp_ = "";

			/**
			 * <code>optional string lookUp = 3;</code>
			 */
			public boolean hasLookUp() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional string lookUp = 3;</code>
			 */
			public java.lang.String getLookUp() {
				java.lang.Object ref = lookUp_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					lookUp_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string lookUp = 3;</code>
			 */
			public com.google.protobuf.ByteString getLookUpBytes() {
				java.lang.Object ref = lookUp_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					lookUp_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string lookUp = 3;</code>
			 */
			public Builder setLookUp(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				lookUp_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string lookUp = 3;</code>
			 */
			public Builder clearLookUp() {
				bitField0_ = (bitField0_ & ~0x00000004);
				lookUp_ = getDefaultInstance().getLookUp();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string lookUp = 3;</code>
			 */
			public Builder setLookUpBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				lookUp_ = value;
				onChanged();
				return this;
			}

			// optional string tcpEndPoint = 4;
			private java.lang.Object tcpEndPoint_ = "";

			/**
			 * <code>optional string tcpEndPoint = 4;</code>
			 */
			public boolean hasTcpEndPoint() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			/**
			 * <code>optional string tcpEndPoint = 4;</code>
			 */
			public java.lang.String getTcpEndPoint() {
				java.lang.Object ref = tcpEndPoint_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					tcpEndPoint_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string tcpEndPoint = 4;</code>
			 */
			public com.google.protobuf.ByteString getTcpEndPointBytes() {
				java.lang.Object ref = tcpEndPoint_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					tcpEndPoint_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string tcpEndPoint = 4;</code>
			 */
			public Builder setTcpEndPoint(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				tcpEndPoint_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string tcpEndPoint = 4;</code>
			 */
			public Builder clearTcpEndPoint() {
				bitField0_ = (bitField0_ & ~0x00000008);
				tcpEndPoint_ = getDefaultInstance().getTcpEndPoint();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string tcpEndPoint = 4;</code>
			 */
			public Builder setTcpEndPointBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				tcpEndPoint_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:Command)
		}

		static {
			defaultInstance = new Command(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:Command)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_Command_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_Command_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\021JoinCommand.proto\"M\n\007Command\022\021\n\tcommnd"
				+ "Val\030\001 \002(\t\022\n\n\002id\030\002 \002(\t\022\016\n\006lookUp\030\003 \001(\t\022\023\n"
				+ "\013tcpEndPoint\030\004 \001(\tB\032\n\013dst.objectsB\013JoinC"
				+ "ommand" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_Command_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_Command_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_Command_descriptor,
						new java.lang.String[] { "CommndVal", "Id", "LookUp",
								"TcpEndPoint", });
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
