// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package dst.objects;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RegistryRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string response = 1;
    /**
     * <code>required string response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>required string response = 1;</code>
     */
    java.lang.String getResponse();
    /**
     * <code>required string response = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();

    // repeated string hosts = 2;
    /**
     * <code>repeated string hosts = 2;</code>
     */
    java.util.List<java.lang.String>
    getHostsList();
    /**
     * <code>repeated string hosts = 2;</code>
     */
    int getHostsCount();
    /**
     * <code>repeated string hosts = 2;</code>
     */
    java.lang.String getHosts(int index);
    /**
     * <code>repeated string hosts = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostsBytes(int index);

    // optional string tcpEndPoint = 3;
    /**
     * <code>optional string tcpEndPoint = 3;</code>
     */
    boolean hasTcpEndPoint();
    /**
     * <code>optional string tcpEndPoint = 3;</code>
     */
    java.lang.String getTcpEndPoint();
    /**
     * <code>optional string tcpEndPoint = 3;</code>
     */
    com.google.protobuf.ByteString
        getTcpEndPointBytes();

    // optional string requestId = 4;
    /**
     * <code>optional string requestId = 4;</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional string requestId = 4;</code>
     */
    java.lang.String getRequestId();
    /**
     * <code>optional string requestId = 4;</code>
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();
  }
  /**
   * Protobuf type {@code RegistryResp}
   */
  public static final class RegistryResp extends
      com.google.protobuf.GeneratedMessage
      implements RegistryRespOrBuilder {
    // Use RegistryResp.newBuilder() to construct.
    private RegistryResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RegistryResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RegistryResp defaultInstance;
    public static RegistryResp getDefaultInstance() {
      return defaultInstance;
    }

    public RegistryResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RegistryResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              response_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                hosts_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              hosts_.add(input.readBytes());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              tcpEndPoint_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              requestId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          hosts_ = new com.google.protobuf.UnmodifiableLazyStringList(hosts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dst.objects.Response.internal_static_RegistryResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dst.objects.Response.internal_static_RegistryResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dst.objects.Response.RegistryResp.class, dst.objects.Response.RegistryResp.Builder.class);
    }

    public static com.google.protobuf.Parser<RegistryResp> PARSER =
        new com.google.protobuf.AbstractParser<RegistryResp>() {
      public RegistryResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegistryResp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RegistryResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string response = 1;
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private java.lang.Object response_;
    /**
     * <code>required string response = 1;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string response = 1;</code>
     */
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          response_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string response = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string hosts = 2;
    public static final int HOSTS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList hosts_;
    /**
     * <code>repeated string hosts = 2;</code>
     */
    public java.util.List<java.lang.String>
        getHostsList() {
      return hosts_;
    }
    /**
     * <code>repeated string hosts = 2;</code>
     */
    public int getHostsCount() {
      return hosts_.size();
    }
    /**
     * <code>repeated string hosts = 2;</code>
     */
    public java.lang.String getHosts(int index) {
      return hosts_.get(index);
    }
    /**
     * <code>repeated string hosts = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostsBytes(int index) {
      return hosts_.getByteString(index);
    }

    // optional string tcpEndPoint = 3;
    public static final int TCPENDPOINT_FIELD_NUMBER = 3;
    private java.lang.Object tcpEndPoint_;
    /**
     * <code>optional string tcpEndPoint = 3;</code>
     */
    public boolean hasTcpEndPoint() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string tcpEndPoint = 3;</code>
     */
    public java.lang.String getTcpEndPoint() {
      java.lang.Object ref = tcpEndPoint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tcpEndPoint_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tcpEndPoint = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTcpEndPointBytes() {
      java.lang.Object ref = tcpEndPoint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tcpEndPoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string requestId = 4;
    public static final int REQUESTID_FIELD_NUMBER = 4;
    private java.lang.Object requestId_;
    /**
     * <code>optional string requestId = 4;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string requestId = 4;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      response_ = "";
      hosts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      tcpEndPoint_ = "";
      requestId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResponse()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResponseBytes());
      }
      for (int i = 0; i < hosts_.size(); i++) {
        output.writeBytes(2, hosts_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getTcpEndPointBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getRequestIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResponseBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hosts_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(hosts_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getHostsList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTcpEndPointBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRequestIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static dst.objects.Response.RegistryResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dst.objects.Response.RegistryResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dst.objects.Response.RegistryResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dst.objects.Response.RegistryResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dst.objects.Response.RegistryResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dst.objects.Response.RegistryResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static dst.objects.Response.RegistryResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static dst.objects.Response.RegistryResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static dst.objects.Response.RegistryResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dst.objects.Response.RegistryResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dst.objects.Response.RegistryResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RegistryResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements dst.objects.Response.RegistryRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dst.objects.Response.internal_static_RegistryResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dst.objects.Response.internal_static_RegistryResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dst.objects.Response.RegistryResp.class, dst.objects.Response.RegistryResp.Builder.class);
      }

      // Construct using dst.objects.Response.RegistryResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        response_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        hosts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        tcpEndPoint_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dst.objects.Response.internal_static_RegistryResp_descriptor;
      }

      public dst.objects.Response.RegistryResp getDefaultInstanceForType() {
        return dst.objects.Response.RegistryResp.getDefaultInstance();
      }

      public dst.objects.Response.RegistryResp build() {
        dst.objects.Response.RegistryResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dst.objects.Response.RegistryResp buildPartial() {
        dst.objects.Response.RegistryResp result = new dst.objects.Response.RegistryResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.response_ = response_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          hosts_ = new com.google.protobuf.UnmodifiableLazyStringList(
              hosts_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.hosts_ = hosts_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tcpEndPoint_ = tcpEndPoint_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestId_ = requestId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dst.objects.Response.RegistryResp) {
          return mergeFrom((dst.objects.Response.RegistryResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dst.objects.Response.RegistryResp other) {
        if (other == dst.objects.Response.RegistryResp.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          bitField0_ |= 0x00000001;
          response_ = other.response_;
          onChanged();
        }
        if (!other.hosts_.isEmpty()) {
          if (hosts_.isEmpty()) {
            hosts_ = other.hosts_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHostsIsMutable();
            hosts_.addAll(other.hosts_);
          }
          onChanged();
        }
        if (other.hasTcpEndPoint()) {
          bitField0_ |= 0x00000004;
          tcpEndPoint_ = other.tcpEndPoint_;
          onChanged();
        }
        if (other.hasRequestId()) {
          bitField0_ |= 0x00000008;
          requestId_ = other.requestId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResponse()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dst.objects.Response.RegistryResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dst.objects.Response.RegistryResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string response = 1;
      private java.lang.Object response_ = "";
      /**
       * <code>required string response = 1;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string response = 1;</code>
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string response = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string response = 1;</code>
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string response = 1;</code>
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000001);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <code>required string response = 1;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        response_ = value;
        onChanged();
        return this;
      }

      // repeated string hosts = 2;
      private com.google.protobuf.LazyStringList hosts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHostsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          hosts_ = new com.google.protobuf.LazyStringArrayList(hosts_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string hosts = 2;</code>
       */
      public java.util.List<java.lang.String>
          getHostsList() {
        return java.util.Collections.unmodifiableList(hosts_);
      }
      /**
       * <code>repeated string hosts = 2;</code>
       */
      public int getHostsCount() {
        return hosts_.size();
      }
      /**
       * <code>repeated string hosts = 2;</code>
       */
      public java.lang.String getHosts(int index) {
        return hosts_.get(index);
      }
      /**
       * <code>repeated string hosts = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostsBytes(int index) {
        return hosts_.getByteString(index);
      }
      /**
       * <code>repeated string hosts = 2;</code>
       */
      public Builder setHosts(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHostsIsMutable();
        hosts_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hosts = 2;</code>
       */
      public Builder addHosts(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHostsIsMutable();
        hosts_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hosts = 2;</code>
       */
      public Builder addAllHosts(
          java.lang.Iterable<java.lang.String> values) {
        ensureHostsIsMutable();
        super.addAll(values, hosts_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hosts = 2;</code>
       */
      public Builder clearHosts() {
        hosts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hosts = 2;</code>
       */
      public Builder addHostsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHostsIsMutable();
        hosts_.add(value);
        onChanged();
        return this;
      }

      // optional string tcpEndPoint = 3;
      private java.lang.Object tcpEndPoint_ = "";
      /**
       * <code>optional string tcpEndPoint = 3;</code>
       */
      public boolean hasTcpEndPoint() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string tcpEndPoint = 3;</code>
       */
      public java.lang.String getTcpEndPoint() {
        java.lang.Object ref = tcpEndPoint_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tcpEndPoint_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tcpEndPoint = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTcpEndPointBytes() {
        java.lang.Object ref = tcpEndPoint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tcpEndPoint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tcpEndPoint = 3;</code>
       */
      public Builder setTcpEndPoint(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tcpEndPoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tcpEndPoint = 3;</code>
       */
      public Builder clearTcpEndPoint() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tcpEndPoint_ = getDefaultInstance().getTcpEndPoint();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tcpEndPoint = 3;</code>
       */
      public Builder setTcpEndPointBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tcpEndPoint_ = value;
        onChanged();
        return this;
      }

      // optional string requestId = 4;
      private java.lang.Object requestId_ = "";
      /**
       * <code>optional string requestId = 4;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string requestId = 4;</code>
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestId = 4;</code>
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 4;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestId = 4;</code>
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        requestId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RegistryResp)
    }

    static {
      defaultInstance = new RegistryResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RegistryResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistryResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RegistryResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\"W\n\014RegistryResp\022\020\n\010resp" +
      "onse\030\001 \002(\t\022\r\n\005hosts\030\002 \003(\t\022\023\n\013tcpEndPoint" +
      "\030\003 \001(\t\022\021\n\trequestId\030\004 \001(\tB\027\n\013dst.objects" +
      "B\010Response"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RegistryResp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RegistryResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RegistryResp_descriptor,
              new java.lang.String[] { "Response", "Hosts", "TcpEndPoint", "RequestId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
